### ISSUE TITLE
Missing changelog

### ISSUE THREAD

**Issue by expipiplus1** [mitchellwrosen/tasty-hspec#11]
It would be nice to have `changelog.md` to help people determine feature changes between versions.

**Comment by mitchellwrosen** [comment]
Ah, I'll try to put one together soon. In the meantime, you can use https://hackage.haskell.org/package/hackage-diff

This repo doesn't seem to change much, however. Mostly when `hspec` breaks and people complain I dig around and figure out what's changed.

**Comment by mitchellwrosen** [comment]
I've added a changelog to the repo, thanks

**Comment by expipiplus1** [comment]
Thanks!
