### ISSUE TITLE
How do you use tasty-hspec?

### ISSUE THREAD

**Issue by uunsamp** [mitchellwrosen/tasty-hspec#12]
Can you give an example of how to use tasty-hspec? 

This is related to #9 I guess.

**Comment by mitchellwrosen** [comment]
Sure. Say you have an existing hspec `Spec` that you want to plug into a `tasty` test suite instead. Simply use `testSpec` in `main`, then build your `tasty` suite with it.

Awkwardly, building the spec tree happens in `IO` - I'm not totally sure why, as I haven't poked around the `hspec` internals much.

```haskell
main = do
  tree <- Hspec.testSpec "blah" mySpec
  ...
```

Does that help?

**Comment by uunsamp** [comment]
@mitchellwrosen Thanks for the response. How does that translate to what I've attempted to so far? 

```
import Test.Tasty
import Test.Tasty.SmallCheck as SC
import Test.Tasty.QuickCheck as QC
import Test.Tasty.Hspec as Hspec

import Data.List
import Data.Ord
import Control.Exception (evaluate)

main = defaultMain tests

tests :: TestTree
tests = testGroup "Tests" [properties, unitTests]

properties :: TestTree
properties = testGroup "Properties" [scProps, qcProps]

scProps = testGroup "(checked by SmallCheck)"
  [ SC.testProperty "sort == sort . reverse" $
      \list -> sort (list :: [Int]) == sort (reverse list)
  , SC.testProperty "Fermat's little theorem" $
      \x -> ((x :: Integer)^7 - x) `mod` 7 == 0
  -- the following property does not hold
  , SC.testProperty "Fermat's last theorem" $
      \x y z n ->
        (n :: Integer) >= 3 SC.==> x^n + y^n /= (z^n :: Integer)
  ]

qcProps = testGroup "(checked by QuickCheck)"
  [ QC.testProperty "sort == sort . reverse" $
      \list -> sort (list :: [Int]) == sort (reverse list)
  , QC.testProperty "Fermat's little theorem" $
      \x -> ((x :: Integer)^7 - x) `mod` 7 == 0
  -- the following property does not hold
  , QC.testProperty "Fermat's last theorem" $
      \x y z n ->
        (n :: Integer) >= 3 QC.==> x^n + y^n /= (z^n :: Integer)
  ]


unitTests = testGroup "(checked by Hspec)"
  [ Hspec.describe "Prelude.head" $ do
    Hspec.it "returns the first element of a list" $ do
      head [23 ..] `Hspec.shouldBe` (23 :: Int)
  , Hspec.describe "Prelude.head" $ do
    Hspec.it "returns the first element of an *arbitrary* list" $
      QC.property $ \x xs -> head (x:xs) == (x :: Int)
  , Hspec.describe "Prelude.head" $ do
    Hspec.it "throws an exception if used with an empty list" $ do
      evaluate (head []) `Hspec.shouldThrow` Hspec.anyException
  ]

```

**Comment by mitchellwrosen** [comment]
I can't help but feel like you didn't read what I wrote, but maybe I wasn't clear. Apologies! Here:

Use `testSpec` in `main`:

```haskell
main = do
  unitTestsTree <- HSpec.testSpec "(checked by Hspec)" unitTests
  defaultMain (testGroup "tests" [properties, scProps qcProps unitTestsTree])

**Comment by uunsamp** [comment]
Thanks! This works now :)

```
import Test.Tasty
import Test.Tasty.SmallCheck as SC
import Test.Tasty.QuickCheck as QC
import Test.Tasty.Hspec as Hspec

import Data.List
import Data.Ord
import Control.Exception (evaluate)

main = do
    unitTestsTree <- Hspec.testSpec "(checked by Hspec)" unitTests
    defaultMain (testGroup "tests" [properties, unitTestsTree])

properties :: TestTree
properties = testGroup "Properties" [scProps, qcProps]

scProps = testGroup "(checked by SmallCheck)"
  [ SC.testProperty "sort == sort . reverse" $
      \list -> sort (list :: [Int]) == sort (reverse list)
  , SC.testProperty "Fermat's little theorem" $
      \x -> ((x :: Integer)^7 - x) `mod` 7 == 0
  -- the following property does not hold
  , SC.testProperty "Fermat's last theorem" $
      \x y z n ->
        (n :: Integer) >= 3 SC.==> x^n + y^n /= (z^n :: Integer)
  ]

qcProps = testGroup "(checked by QuickCheck)"
  [ QC.testProperty "sort == sort . reverse" $
      \list -> sort (list :: [Int]) == sort (reverse list)
  , QC.testProperty "Fermat's little theorem" $
      \x -> ((x :: Integer)^7 - x) `mod` 7 == 0
  -- the following property does not hold
  , QC.testProperty "Fermat's last theorem" $
      \x y z n ->
        (n :: Integer) >= 3 QC.==> x^n + y^n /= (z^n :: Integer)
  ]


unitTests = Hspec.describe "Prelude.head" $ do
  Hspec.it "returns the first element of a list" $ do
    head [23 ..] `Hspec.shouldBe` (23 :: Int)
  Hspec.it "returns the first element of an *arbitrary* list" $
    QC.property $ \x xs -> head (x:xs) == (x :: Int)
  Hspec.it "throws an exception if used with an empty list" $ do
    evaluate (head []) `Hspec.shouldThrow` Hspec.anyException
```

**Comment by mitchellwrosen** [comment]
Great! Shall I close?

**Comment by liskin** [comment]
_hspec_ lets you do IO when building the spec tree. I imagine it's intended for e.g. loading config files and using them during the spec tree preparation phase. And since _tasty_ doesn't have this ability, you can't just translate this IO into a _tasty_ primitive, but need to actually perform it in `testSpec` in the translation phase.

But I wouldn't hesitate to use `unsafePerformIO` if I needed to use `testSpec` deep in a _tasty_ `TestTree`. :-)

**Comment by mitchellwrosen** [comment]
@liskin Thanks, I figured that was the case. I agree that `unsafePerformIO` is probably the correct way to integrate a hspec tree into a tasty tree (since performing `IO` during test tree generation already makes the test suite non-referentially transparent), however I'm not totally sure this library should do the `unsafePerformIO` for you.

What do you think?

**Comment by liskin** [comment]
Yeah, it probably shouldn't. I'm not proposing that. Just stumbled upon this and saw that you never explained the IO issue, and as I needed to understand it myself anyway, I thought I would just write my thoughts down somewhere. :-)

**Comment by wjrforcyber** [comment]
> Thanks! This works now :)
> 
> ```haskell
> import Test.Tasty
> import Test.Tasty.SmallCheck as SC
> import Test.Tasty.QuickCheck as QC
> import Test.Tasty.Hspec as Hspec
> 
> import Data.List
> import Data.Ord
> import Control.Exception (evaluate)
> 
> main = do
>     unitTestsTree <- Hspec.testSpec "(checked by Hspec)" unitTests
>     defaultMain (testGroup "tests" [properties, unitTestsTree])
> 
> properties :: TestTree
> properties = testGroup "Properties" [scProps, qcProps]
> 
> scProps = testGroup "(checked by SmallCheck)"
>   [ SC.testProperty "sort == sort . reverse" $
>       \list -> sort (list :: [Int]) == sort (reverse list)
>   , SC.testProperty "Fermat's little theorem" $
>       \x -> ((x :: Integer)^7 - x) `mod` 7 == 0
>   -- the following property does not hold
>   , SC.testProperty "Fermat's last theorem" $
>       \x y z n ->
>         (n :: Integer) >= 3 SC.==> x^n + y^n /= (z^n :: Integer)
>   ]
> 
> qcProps = testGroup "(checked by QuickCheck)"
>   [ QC.testProperty "sort == sort . reverse" $
>       \list -> sort (list :: [Int]) == sort (reverse list)
>   , QC.testProperty "Fermat's little theorem" $
>       \x -> ((x :: Integer)^7 - x) `mod` 7 == 0
>   -- the following property does not hold
>   , QC.testProperty "Fermat's last theorem" $
>       \x y z n ->
>         (n :: Integer) >= 3 QC.==> x^n + y^n /= (z^n :: Integer)
>   ]
> 
> unitTests = Hspec.describe "Prelude.head" $ do
>   Hspec.it "returns the first element of a list" $ do
>     head [23 ..] `Hspec.shouldBe` (23 :: Int)
>   Hspec.it "returns the first element of an *arbitrary* list" $
>     QC.property $ \x xs -> head (x:xs) == (x :: Int)
>   Hspec.it "throws an exception if used with an empty list" $ do
>     evaluate (head []) `Hspec.shouldThrow` Hspec.anyException
> ```

This seems doesn't work any more in 2021, I still use the same structure. But no matter I use "describe" or "Hspec.desribe" it always shows an error.
`app\Experiments\Tests.hs:234:3: error:
    Variable not in scope: describe :: String -> t0 -> m a1
    |
234 |   describe "test1" $
    |   ^^^^^^^^
`

or

`app\Experiments\Tests.hs:234:3: error:
    Not in scope: ‘Hspec.describe’
    Module ‘Test.Tasty.Hspec’ does not export ‘describe’.
    |
234 |   Hspec.describe "test1" $
    |   ^^^^^^^^^^^^^^
`
Don't know why, may need your help Sir @mitchellwrosen . :(

**Comment by mitchellwrosen** [comment]
Sorry about that. Recently `tasty-hspec` stopped re-exporting `hspec`'s symbols entirely, so you'll have to get `describe` from `hspec`.
