### ISSUE TITLE
Support building with hspec 2.5

### ISSUE THREAD

**Issue by DanBurton** [mitchellwrosen/tasty-hspec#17]
https://github.com/mitchellwrosen/tasty-hspec/blob/b2d6fa57d0c9053a49e96c149e3ad9c6865928cd/tasty-hspec.cabal#L48

**Comment by mitchellwrosen** [comment]
Thanks, I'll update :)

Totally irrelevant complaint: I just tried building this repo (which lacks a `stack.yaml`) on my new laptop. First step, bootstrap `cabal`. Second step, build `cabal-HEAD` with `cabal`!

```
$ cd haskell/cabal
$ cabal new-build cabal-install
...
Configuring library for pretty-show-1.6.16..
Preprocessing library for pretty-show-1.6.16..
happy: /home/mitchell/haskell/x/.cabal-sandbox/share/x86_64-linux-ghc-8.2.2/happy-1.19.8/HappyTemplate-arrays-coerce: openFile: does not exist (No such file or directory)
cabal: Failed to build pretty-show-1.6.16 (which is required by
cabal-install-2.3.0.0).
```

What the hell is that?! Somehow during building, `happy` is is trying to access an `x/` directory _up one level_ from the current (`/home/mitchell/haskell/cabal/`).

**Comment by mitchellwrosen** [comment]
1.1.4 uploaded
