### ISSUE TITLE
TreatPendingAs "Data constructor not in scope"

### ISSUE THREAD

**Issue by amiri** [mitchellwrosen/tasty-hspec#19]
I am trying to use `localOption` to set `TreatPendingAs`, and it doesn't seem to work. I have a tasty test suite in which I am using Test.Tasty.Hspec.

```
import           Test.Tasty (TestTree, localOption, testGroup)
import           Test.Tasty.Hspec

tests :: TestTree
tests = localOption (TreatPendingAs Success) $ testGroup "Api"
    $ [unsafePerformIO (testSpec "servant-quickcheck" spec_servantQuickCheck)]
```
I keep getting

```
    Data constructor not in scope:
      TreatPendingAs :: TreatPendingAs -> v0
   |
48 | tests = localOption (TreatPendingAs Success) $ testGroup "Api"

```

I can set this option on the command line with `stack test --test-arguments '--treat-pending-as success'`, but why doesn't `localOption` work?

**Comment by mitchellwrosen** [comment]
The data constructor is called `Success`. Try:

```
localOption Success $ ...
```

(And I should probably rename the constructor to `TreatPendingAsSuccess`, shouldn't I :))
