### ISSUE TITLE
Support for GHC 9.0.1

### ISSUE THREAD

**Issue by sjakobi** [mitchellwrosen/tasty-hspec#23]
I believe the `base` bound can simply be relaxed.

**Comment by sjakobi** [comment]
Ping @mitchellwrosen! :)

**Comment by mitchellwrosen** [comment]
Oops, thanks for the ping! Taking care of this now.

**Comment by mitchellwrosen** [comment]
:ok_hand: released as 1.1.6 revision 1

**Comment by sjakobi** [comment]
Thank you! :)
