### ISSUE TITLE
Compatibility with hspec 2.9

### ISSUE THREAD

**Issue by sjakobi** [mitchellwrosen/tasty-hspec#27]
https://hackage.haskell.org/package/hspec-2.9.0/changelog

Could you make a compatible release? Thanks! :)

**Comment by mitchellwrosen** [comment]
Done, thanks for the ping!

**Comment by sjakobi** [comment]
Thanks for the quick response! Could make a release or Hackage revision?

**Comment by mitchellwrosen** [comment]
Yup, it was released as a revision.

**Comment by mitchellwrosen** [comment]
... no it wasn't. 🤦‍♂️ Will push tonight.

**Comment by mitchellwrosen** [comment]
Note to self and others:

```
hackage-cli push-cabal tasty-hspec.cabal
```

!=

```
hackage-cli push-cabal tasty-hspec.cabal --publish
```

**Comment by sjakobi** [comment]
Cheers! :grin:
