### ISSUE TITLE
Compatibility with Hspec 2.10

### ISSUE THREAD

**Issue by LaurentRDC** [mitchellwrosen/tasty-hspec#29]
Hello,

I just started getting build errors with `tasty-hspec`, as soon as `hspec`/`hspec-core` 2.10 was released this morning. Would you be able to update the  bounds on Hackage to `hspec`/`hspec-core < 2.10`?

Thanks!

**Comment by sjakobi** [comment]
@LaurentRDC Which versions did you get build errors with? I can't actually find any build plans with `hspec-2.10`, except with `tasty-hspec-0.1.0.1`, and those look OK.

**Comment by LaurentRDC** [comment]
I am so sorry, I forgot I set `allow-newer: all` in my project file...

I apologize for the confusion.

**Comment by mitchellwrosen** [comment]
Thanks; I've uploaded a new version with hspec-2.10.0 compatibility: https://hackage.haskell.org/package/tasty-hspec-1.2.0.1
