### ISSUE TITLE
Please consider registering this package to Stackage

### ISSUE THREAD

**Issue by cies** [mitchellwrosen/tasty-hspec#6]
[Stackage](http://stackage.org) is a set of Haskell packages that is known to compile together. Most `tasty-*` providers are already on Stackage (see [here](http://www.stackage.org/lts) and find `tasty-`), and HSpec is on Stackage as well... I have a package that uses `tasty-hspec` that --once registered in Stackage-- could not be "tested" (only the test suite depends on `tasty-hspec`) as part of Stackage because of it's dependency on this package.

Thanks for considering!

**Comment by mitchellwrosen** [comment]
Done =)
