### ISSUE TITLE
Fails to build with GHC 7.6

### ISSUE THREAD

**Issue by tfausak** [mitchellwrosen/tasty-hspec#7]
This package uses [`Data.Proxy` from the `base` package](https://hackage.haskell.org/package/base-4.8.0.0/docs/Data-Proxy.html). Unfortunately that was added in version 4.7, so it's not available with GHC 7.6. 

```
Test/Tasty/Hspec.hs:20:18:
    Could not find module `Data.Proxy'
    It is a member of the hidden package `tagged-0.8.0.1'.
    Perhaps you need to add `tagged' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

https://travis-ci.org/tfausak/haskeleton/jobs/64844814#L474-L478

I think this could be solved by either adding a dependency on [`base-compat`](http://hackage.haskell.org/package/base-compat) or [`tagged`](http://hackage.haskell.org/package/tagged).

**Comment by mitchellwrosen** [comment]
Mind making a PR? =)

**Comment by tfausak** [comment]
I think the issue may actually be with my library. I see that a dependency on tagged was added in 7bf414328fbcd10ce26325bc5dc7a3503a9268a5, and that you test against GHC 7.6 on Travis CI.

**Comment by mitchellwrosen** [comment]
@tfausak Can I close this issue?

**Comment by tfausak** [comment]
:+1:
