### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by fatlazycat** [mitchellwrosen/tasty-hspec#9]
Hi, do you have an example usages of tasty-hspec when joining it with say hunit / quick check tests that are not coded up in the hspec style i.e. from tasty-hunit, tasty-quickcheck ?

Thanks

**Comment by mitchellwrosen** [comment]
I'm not sure I understand :)

`tasty-hspec` allows you to take your `Spec`s and convert them to tasty's `TestTree`, to be run with `defaultMain` and so forth. Annoyingly, it's not a pure function - maybe I'll look back over the API and see if I'm doing something dumb.

**Comment by fatlazycat** [comment]
Ha i think it's me being dumb :) Just learning Haskell but have sorted it now thanks and combined them.

Though did wonder why it wasn't a pure fn :)
